# Generated by Django 5.2.15 on 2026-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproductcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('RABBIT', 'Rabbit'), ('HAMSTER', 'Hamster'), ('BIRD', 'Bird'), ('FISH', 'Fish'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('BABY', 'Baby'), ('PUPPY', 'Puppy'), ('KITTEN', 'Kitten'), ('ADULT', 'Adult'), ('SENIOR', 'Senior'), ('ALL', 'All ages')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.producttag'),
        ),
    ]
