# Generated by Django 5.2.15 on 2026-06-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('categories', 'Categories'), ('brands', 'Brands'), ('suppliers', 'Suppliers'), ('products', 'Products'), ('stock_in', 'Stock-In')], max_length=40)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('COMMITTED', 'Committed')], default='PREVIEW', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_upload_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('is_selected', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('committed_action', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='batch_upload.batchuploadjob')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='batchuploadjob',
            index=models.Index(fields=['target', 'status'], name='batch_uploa_target_2307e6_idx'),
        ),
        migrations.AddIndex(
            model_name='batchuploadjob',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='batch_uploa_uploade_0bae7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchuploadrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='unique_batch_upload_job_row_number'),
        ),
    ]
