# Generated by Django 5.2.15 on 2026-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('template_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SHELF', 'Shelf'), ('PROMOTION', 'Promotion'), ('CUSTOM', 'Custom')], default='PRODUCT', max_length=20)),
                ('paper_width_mm', models.PositiveIntegerField(default=50)),
                ('paper_height_mm', models.PositiveIntegerField(default=30)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=20)),
                ('font_size_px', models.PositiveIntegerField(default=11)),
                ('show_store_name', models.BooleanField(default=True)),
                ('show_logo', models.BooleanField(default=False)),
                ('show_product_name', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_sku', models.BooleanField(default=False)),
                ('show_barcode', models.BooleanField(default=True)),
                ('show_qr', models.BooleanField(default=False)),
                ('show_batch', models.BooleanField(default=True)),
                ('show_expiry', models.BooleanField(default=True)),
                ('show_animal_type', models.BooleanField(default=False)),
                ('show_life_stage', models.BooleanField(default=False)),
                ('header_text', models.CharField(blank=True, max_length=120)),
                ('custom_footer', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
