# Generated by Django 5.2.15 on 2026-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Melodu Pet Store', max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('receipt_header', models.CharField(blank=True, max_length=255)),
                ('receipt_footer', models.CharField(blank=True, default='Thank you!', max_length=255)),
                ('receipt_paper_width_mm', models.PositiveIntegerField(default=80)),
                ('receipt_font_size_px', models.PositiveIntegerField(default=12)),
                ('show_logo_on_receipt', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(default='$', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store setting',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
