#!/usr/bin/env python3
"""Regenerate the ICONS dict in melodu_icons.py from vendored Tabler SVGs.

The icon set is Tabler Icons (MIT), vendored under vendor/tabler-icons/ at the
pinned tag in TABLER_VERSION. Nothing is fetched at build or request time — the
POS is a PWA that must install and run offline, so every icon ships inline.

Adding an icon:
    1. add "melodu-name": "tabler-file-name" to MAPPING below
    2. drop the SVG into vendor/tabler-icons/ (from the pinned tag)
    3. python3 scripts/sync_icons.py

Never hand-draw paths: a hand-drawn imitation is exactly what this replaced.
Run with --check to fail if the generated block is stale (for CI).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TABLER_VERSION = "v3.31.0"
ROOT = Path(__file__).resolve().parent.parent
VENDOR = ROOT / "vendor" / "tabler-icons"
TARGET = ROOT / "app" / "core" / "templatetags" / "melodu_icons.py"

BEGIN = "    # >>> generated by scripts/sync_icons.py — do not edit by hand"
END = "    # <<< end generated"

# Melodu name -> Tabler outline file. The 32 V7 names keep their names, so no
# template changes; the rest are the vocabulary V8 phases 4-6 need.
MAPPING = {
    # --- V7 set: same names, now the real Tabler glyphs ---
    "activity": "activity",
    "alert": "alert-triangle",
    "barcode": "barcode",
    "camera": "camera",
    "cart": "shopping-cart",
    "cash": "cash",
    "category": "category",
    "chart": "chart-bar",
    "check": "check",
    "clock": "clock",
    "dollar": "currency-dollar",
    "hold": "player-pause",
    "home": "home",
    "logout": "logout",
    "logs": "file-text",
    "package": "package",
    "percent": "percentage",
    "plus": "plus",
    "printer": "printer",
    "receipt": "receipt",
    "scan": "scan",
    "search": "search",
    "settings": "settings",
    "shield": "shield-check",
    "sidebar": "layout-sidebar",
    "tag": "tag",
    "trend-up": "trending-up",
    "truck": "truck-delivery",
    "upload": "upload",
    "user": "user",
    "users": "users",
    "x": "x",
    # --- V8 additions: collapsible nav, grid/table toggle, media, row actions ---
    "calendar": "calendar",
    "chevron-down": "chevron-down",
    "chevron-left": "chevron-left",
    "chevron-right": "chevron-right",
    "dots": "dots-vertical",
    "edit": "edit",
    "eye": "eye",
    "filter": "filter",
    "grid": "layout-grid",
    "list": "list",
    "photo": "photo",
    "photo-plus": "photo-plus",
    "refresh": "refresh",
    "trash": "trash",
}


def inner_markup(svg_path: Path) -> str:
    """Reduce a Tabler SVG to the inner shapes the {% icon %} tag wraps.

    The wrapper (24x24 viewBox, currentColor, stroke-width 1.8, round caps) is
    owned by the template tag, so only child elements are kept. Tabler ships
    some icons with a transparent 24x24 guide rect; it is dropped.
    """
    raw = svg_path.read_text()
    raw = re.sub(r"<!--.*?-->", "", raw, flags=re.S)
    open_tag = re.search(r"<svg\b[^>]*>", raw, flags=re.S)
    if not open_tag:
        raise SystemExit(f"{svg_path.name}: no <svg> element")
    inner = raw[open_tag.end() : raw.rindex("</svg>")]
    inner = re.sub(r'<path\s+stroke="none"[^>]*/>', "", inner)
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = re.sub(r"\s*/>", "/>", inner)
    inner = inner.replace("> <", "><")
    if not inner:
        raise SystemExit(f"{svg_path.name}: reduced to nothing")
    if "'" in inner:
        raise SystemExit(f"{svg_path.name}: single quote would break the literal")
    return inner


def build_block() -> str:
    lines = [BEGIN, f"    # Tabler Icons (MIT) {TABLER_VERSION} — vendor/tabler-icons/"]
    for name in sorted(MAPPING):
        svg = VENDOR / f"{MAPPING[name]}.svg"
        if not svg.exists():
            raise SystemExit(f"missing vendored icon: {svg.relative_to(ROOT)}")
        lines.append(f"    {name!r}: '{inner_markup(svg)}',")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true", help="fail if regeneration would change the file"
    )
    args = ap.parse_args()

    src = TARGET.read_text()
    block = build_block()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(src):
        raise SystemExit(f"{TARGET.name}: generated markers not found")
    updated = pattern.sub(lambda _: block, src)

    if args.check:
        if updated != src:
            print(
                "melodu_icons.py is stale — run: python3 scripts/sync_icons.py",
                file=sys.stderr,
            )
            return 1
        print(f"melodu_icons.py is up to date ({len(MAPPING)} icons)")
        return 0

    TARGET.write_text(updated)
    print(f"wrote {len(MAPPING)} icons to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
