#!/usr/bin/env python3
"""Regenerate the ICONS dict in melodu_icons.py from vendored Tabler SVGs.

The icon set is Tabler Icons (MIT), vendored under vendor/tabler-icons/ at the
pinned tag in TABLER_VERSION. Nothing is fetched at build or request time — the
POS is a PWA that must install and run offline, so every icon ships inline.

Adding an icon:
    1. add "melodu-name": "tabler-file-name" to MAPPING below
    2. drop the SVG into vendor/tabler-icons/ (from the pinned tag)
    3. python3 scripts/sync_icons.py

Never hand-draw paths: a hand-drawn imitation is exactly what this replaced.
Run with --check to fail if the generated block is stale (for CI).
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from xml.etree import ElementTree

TABLER_VERSION = "v3.31.0"
ROOT = Path(__file__).resolve().parent.parent
VENDOR = ROOT / "vendor" / "tabler-icons"
TARGET = ROOT / "app" / "core" / "templatetags" / "melodu_icons.py"

BEGIN = "    # >>> generated by scripts/sync_icons.py — do not edit by hand"
END = "    # <<< end generated"

# Melodu name -> Tabler outline file. The 32 V7 names keep their names, so no
# template changes; the rest are the vocabulary V8 phases 4-6 need.
MAPPING = {
    # --- V7 set: same names, now the real Tabler glyphs ---
    "activity": "activity",
    "alert": "alert-triangle",
    "barcode": "qrcode",  # not `barcode`: shares scan's bracket silhouette, and 1-unit bars fill solid
    "camera": "camera",
    "cart": "shopping-cart",
    "cash": "cash",
    "category": "category",
    "chart": "chart-bar",
    "check": "check",
    "clock": "clock",
    "dollar": "currency-dollar",
    "hold": "player-pause",
    "home": "home",
    "logout": "logout",
    "logs": "file-text",
    "package": "package",
    "percent": "percentage",
    "plus": "plus",
    "printer": "printer",
    "receipt": "receipt",
    "scan": "scan",
    "search": "search",
    "settings": "adjustments",  # not `settings`: the 12-lobe cog smudges below 16px
    "shield": "shield",  # not `shield-check`: its open outline fragments below 16px
    "sidebar": "layout-sidebar",
    "tag": "tag",
    "trend-up": "trending-up",
    "truck": "truck",  # not `truck-delivery`: the broken cargo wall reads as noise at 17px
    "upload": "upload",
    "user": "user",
    "users": "users",
    "x": "x",
    # --- V8 additions: collapsible nav, grid/table toggle, media, row actions ---
    "calendar": "calendar",
    "chevron-down": "chevron-down",
    "chevron-left": "chevron-left",
    "chevron-right": "chevron-right",
    "dots": "dots-vertical",
    "edit": "edit",
    "eye": "eye",
    "filter": "filter",
    "grid": "layout-grid",
    "list": "list",
    "photo": "photo",
    "photo-plus": "photo-plus",
    "refresh": "refresh",
    "trash": "trash",
}


ALLOWED_TAGS = {"path", "circle", "rect", "line", "polyline", "polygon", "ellipse"}
ALLOWED_ATTRS = {
    "d", "cx", "cy", "r", "rx", "ry", "x", "y", "x1", "y1", "x2", "y2",
    "width", "height", "points", "transform", "fill", "stroke",
    "stroke-width", "stroke-linecap", "stroke-linejoin",
}


def ET_OK(fragment: str) -> bool:
    try:
        ElementTree.fromstring(fragment)
    except ElementTree.ParseError:
        return False
    return True


def inner_markup(svg_path: Path) -> str:
    """Reduce a Tabler SVG to the inner shapes the {% icon %} tag wraps.

    The wrapper (24x24 viewBox, currentColor, stroke-width 1.8, round caps) is
    owned by the template tag, so only child elements are kept. Tabler ships
    some icons with a transparent 24x24 guide rect; it is dropped.
    """
    raw = svg_path.read_text(encoding="utf-8")
    raw = re.sub(r"<!--.*?-->", "", raw, flags=re.S)
    open_tag = re.search(r"<svg\b[^>]*>", raw, flags=re.S)
    if not open_tag:
        raise SystemExit(f"{svg_path.name}: no <svg> element")
    close = raw.rfind("</svg>")
    if close == -1:
        raise SystemExit(f"{svg_path.name}: no closing </svg>")
    inner = raw[open_tag.end() : close]
    inner = re.sub(r'<path\s+stroke="none"[^>]*/>', "", inner)
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = re.sub(r"\s*/>", "/>", inner)
    inner = inner.replace("> <", "><")
    if not inner:
        raise SystemExit(f"{svg_path.name}: reduced to nothing")

    # The result is handed to mark_safe(), so assert its shape rather than
    # trusting the source: only geometry elements, only geometry attributes.
    # A future Tabler icon carrying <style>, <script>, an href or an on*
    # handler must fail the build, not be injected into every page.
    if not ET_OK(f"<g>{inner}</g>"):
        raise SystemExit(f"{svg_path.name}: reduced markup is not well-formed XML")
    for tag in re.findall(r"<\s*([A-Za-z][\w-]*)", inner):
        if tag not in ALLOWED_TAGS:
            raise SystemExit(f"{svg_path.name}: disallowed element <{tag}>")
    for attr in re.findall(r"([A-Za-z][\w:-]*)\s*=", inner):
        if attr not in ALLOWED_ATTRS:
            raise SystemExit(f"{svg_path.name}: disallowed attribute {attr!r}")
    return inner


def build_block() -> str:
    lines = [
        BEGIN,
        f"    # Tabler Icons {TABLER_VERSION} — MIT, Copyright (c) 2020-2024 Pawel Kuna.",
        "    # Full licence text: vendor/tabler-icons/LICENSE",
    ]
    for name in sorted(MAPPING):
        svg = VENDOR / f"{MAPPING[name]}.svg"
        if not svg.exists():
            raise SystemExit(f"missing vendored icon: {svg.relative_to(ROOT)}")
        lines.append(f"    {name!r}: {inner_markup(svg)!r},")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true", help="fail if regeneration would change the file"
    )
    args = ap.parse_args()

    src = TARGET.read_text(encoding="utf-8")
    block = build_block()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(src):
        raise SystemExit(f"{TARGET.name}: generated markers not found")
    updated = pattern.sub(lambda _: block, src)

    if args.check:
        if updated != src:
            print(
                "melodu_icons.py is stale — run: python3 scripts/sync_icons.py",
                file=sys.stderr,
            )
            return 1
        print(f"melodu_icons.py is up to date ({len(MAPPING)} icons)")
        return 0

    # Write via a sibling temp file + os.replace: a half-written
    # melodu_icons.py would break every page that loads the tag library.
    tmp = TARGET.with_suffix(".py.tmp")
    tmp.write_text(updated, encoding="utf-8")
    os.replace(tmp, TARGET)
    print(f"wrote {len(MAPPING)} icons to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
